// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const AGI_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const AGI_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "National Airspace System",
  "Weather",
  "Flight Planning",
  "Performance and Limitations",
  "Principles of Flight",
  "Aircraft Systems",
  "Flight Instruments",
  "Aeromedical Factors",
  "Instructional Knowledge",
] as const;

export const AGI_QUESTIONS: TestBankQuestion[] = [
  {
    id: "AGI0001",
    aok: "Regulations",
    text: "Under 14 CFR Part 61, what is the minimum number of cross-country flying hours required in a single-engine airplane for a student pilot seeking a private pilot certificate?",
    choices: [
      { key: "A", text: "5 hours as pilot-in-command" },
      { key: "B", text: "10 hours with at least 5 hours solo" },
      { key: "C", text: "15 hours with a certified flight instructor aboard" },
    ],
    correct: "B",
  },
  {
    id: "AGI0002",
    aok: "Regulations",
    text: "A flight instructor is required to endorse a student pilot's logbook for solo flight only after the student has demonstrated proficiency in which of the following?",
    choices: [
      { key: "A", text: "Commercial pilot maneuvers and procedures" },
      { key: "B", text: "Maneuvering with reference to the ground and basic instrument procedures" },
      { key: "C", text: "Navigation to a distant airport and emergency procedures" },
    ],
    correct: "B",
  },
  {
    id: "AGI0003",
    aok: "National Airspace System",
    text: "Which airspace classification requires all aircraft to be equipped with an operable transponder and altitude reporting equipment?",
    choices: [
      { key: "A", text: "Class B and Class C airspace" },
      { key: "B", text: "Class A, B, and C airspace" },
      { key: "C", text: "Class D and all other controlled airspace" },
    ],
    correct: "B",
  },
  {
    id: "AGI0004",
    aok: "National Airspace System",
    text: "What is the maximum speed permitted for aircraft operating within Class B airspace?",
    choices: [
      { key: "A", text: "200 knots indicated airspeed" },
      { key: "B", text: "250 knots indicated airspeed" },
      { key: "C", text: "No speed restriction exists" },
    ],
    correct: "B",
  },
  {
    id: "AGI0005",
    aok: "Weather",
    text: "A student pilot is preparing for a cross-country flight and receives a forecast for moderate turbulence at flight level 80. Which factor would NOT contribute to this turbulence forecast?",
    choices: [
      { key: "A", text: "Mountain wave activity downwind of a ridge" },
      { key: "B", text: "Wind shear at the boundary between air masses" },
      { key: "C", text: "An area of light rain with weak convection" },
    ],
    correct: "C",
  },
  {
    id: "AGI0006",
    aok: "Weather",
    text: "When instructing a student on weather interpretation, you note that the freezing level is at 8,000 feet MSL. What is the primary concern if the student operates at 6,500 feet MSL where visible moisture exists?",
    choices: [
      { key: "A", text: "Icing conditions due to cloud tops" },
      { key: "B", text: "Carburetor ice and structural icing hazards" },
      { key: "C", text: "Convective activity and microbursts" },
    ],
    correct: "B",
  },
  {
    id: "AGI0007",
    aok: "Flight Planning",
    text: "When planning a cross-country flight for a student pilot, what is the minimum visibility requirement and ceiling needed for VFR flight at night?",
    choices: [
      { key: "A", text: "3 statute miles visibility and 1,000 feet ceiling" },
      { key: "B", text: "5 statute miles visibility and 1,000 feet ceiling" },
      { key: "C", text: "VFR night flights are not permitted for student pilots" },
    ],
    correct: "C",
  },
  {
    id: "AGI0008",
    aok: "Flight Planning",
    text: "A student pilot plans a VFR cross-country with a calculated heading of 150° and estimated ground speed of 120 knots. The flight is 180 nautical miles. What is the estimated time en route?",
    choices: [
      { key: "A", text: "0.67 hours" },
      { key: "B", text: "1.0 hour" },
      { key: "C", text: "1.5 hours" },
    ],
    correct: "C",
  },
  {
    id: "AGI0009",
    aok: "Performance and Limitations",
    text: "When teaching a student about aircraft performance, which factor has the GREATEST effect on an airplane's ability to take off from a short runway?",
    choices: [
      { key: "A", text: "Ambient temperature and density altitude" },
      { key: "B", text: "Runway surface friction coefficient" },
      { key: "C", text: "Aircraft weight and center of gravity" },
    ],
    correct: "A",
  },
  {
    id: "AGI0010",
    aok: "Performance and Limitations",
    text: "A student pilot is flying an aircraft with a maximum demonstrated crosswind component of 12 knots. A wind is reported at 320° at 18 knots, and the runway is oriented 310°. What action should the instructor recommend?",
    choices: [
      { key: "A", text: "Land on runway 310 since the airport elevation is below 5,000 feet" },
      { key: "B", text: "Attempt a forward slip to increase descent rate" },
      { key: "C", text: "Request a different runway or divert to an alternate airport" },
    ],
    correct: "C",
  },
  {
    id: "AGI0011",
    aok: "Principles of Flight",
    text: "When instructing a student on the principle of lift, which statement correctly describes the relationship between angle of attack and lift in the normal flight envelope?",
    choices: [
      { key: "A", text: "Lift increases proportionally with any increase in angle of attack" },
      { key: "B", text: "Lift increases with angle of attack until the critical angle is exceeded" },
      { key: "C", text: "Lift decreases as angle of attack increases above 5°" },
    ],
    correct: "B",
  },
  {
    id: "AGI0012",
    aok: "Principles of Flight",
    text: "A student pilot asks why an airplane turns more effectively at a higher bank angle. The primary reason is:",
    choices: [
      { key: "A", text: "The vertical component of lift increases, reducing radius of turn" },
      { key: "B", text: "The horizontal component of lift increases, which provides centripetal force" },
      { key: "C", text: "Drag decreases, allowing for higher true airspeed during the turn" },
    ],
    correct: "B",
  },
  {
    id: "AGI0013",
    aok: "Aircraft Systems",
    text: "When teaching carburetor ice recognition, which flight regime is most susceptible to carburetor ice formation?",
    choices: [
      { key: "A", text: "High-power climbs at full throttle" },
      { key: "B", text: "Cruise flight at moderate power with high humidity" },
      { key: "C", text: "Descent with reduced power in humid conditions" },
    ],
    correct: "C",
  },
  {
    id: "AGI0014",
    aok: "Aircraft Systems",
    text: "A student pilot is learning about the electrical system. If the alternator fails in flight, what is the primary purpose of the battery in the electrical system?",
    choices: [
      { key: "A", text: "To maintain all electrical loads including the engine" },
      { key: "B", text: "To power essential avionics and instruments for a safe landing" },
      { key: "C", text: "To provide backup power for exactly 30 minutes of flight" },
    ],
    correct: "B",
  },
  {
    id: "AGI0015",
    aok: "Flight Instruments",
    text: "When instructing a student on attitude indicator interpretation, which characteristic makes it reliable for instrument flying?",
    choices: [
      { key: "A", text: "It is not affected by gravitational forces or acceleration" },
      { key: "B", text: "It continues to show attitude even if the vacuum system fails" },
      { key: "C", text: "It displays both pitch and bank attitude with minimal lag" },
    ],
    correct: "C",
  },
  {
    id: "AGI0016",
    aok: "Flight Instruments",
    text: "A student pilot observes that the heading indicator shows 200° but the magnetic compass shows 160°. The most likely explanation is:",
    choices: [
      { key: "A", text: "The heading indicator has precessed and needs to be reset to magnetic compass" },
      { key: "B", text: "The aircraft is in a turn and the magnetic compass is lagging" },
      { key: "C", text: "The magnetic compass is unreliable and should be ignored" },
    ],
    correct: "A",
  },
  {
    id: "AGI0017",
    aok: "Aeromedical Factors",
    text: "When instructing about hypoxia, at what approximate altitude does an unaided pilot experience the effects of hypoxia during daytime flight?",
    choices: [
      { key: "A", text: "5,000 feet MSL" },
      { key: "B", text: "8,000 feet MSL" },
      { key: "C", text: "12,000 feet MSL" },
    ],
    correct: "B",
  },
  {
    id: "AGI0018",
    aok: "Aeromedical Factors",
    text: "A student pilot reports vertigo and disorientation during flight. What is the primary vestibular system malfunction responsible?",
    choices: [
      { key: "A", text: "Spatial disorientation from accelerations and turns affecting fluid in the semicircular canals" },
      { key: "B", text: "Loss of oxygen to the inner ear causing permanent hearing loss" },
      { key: "C", text: "Excessive blood sugar leading to impaired balance reflexes" },
    ],
    correct: "A",
  },
  {
    id: "AGI0019",
    aok: "Instructional Knowledge",
    text: "As a flight instructor, when teaching a new procedure to a student, which instructional technique is most effective for initial learning?",
    choices: [
      { key: "A", text: "The tell-show-do method followed by student practice and feedback" },
      { key: "B", text: "Allowing the student to discover the procedure independently" },
      { key: "C", text: "Showing video demonstrations without hands-on practice" },
    ],
    correct: "A",
  },
  {
    id: "AGI0020",
    aok: "Instructional Knowledge",
    text: "When evaluating a student pilot's learning plateau, which strategy should an instructor use to help the student progress?",
    choices: [
      { key: "A", text: "Increase the complexity of maneuvers immediately" },
      { key: "B", text: "Provide positive feedback, identify specific areas for improvement, and vary training methods" },
      { key: "C", text: "Continue with the same lesson plan until proficiency develops" },
    ],
    correct: "B",
  },
];
