// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const ATP_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const ATP_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "Weather",
  "Navigation and Flight Planning",
  "Performance and Limitations",
  "Aerodynamics",
  "Aircraft Systems",
  "Crew Resource Management",
  "Emergency Procedures",
] as const;

export const ATP_QUESTIONS: TestBankQuestion[] = [
  {
    id: "ATP0001",
    aok: "Regulations",
    text: "Under 14 CFR Part 121, what is the maximum duty period for a flight crew member operating under the 1-pilot-in-command exception?",
    choices: [
      { key: "A", text: "8 hours" },
      { key: "B", text: "10 hours" },
      { key: "C", text: "12 hours" },
    ],
    correct: "B",
  },
  {
    id: "ATP0002",
    aok: "Regulations",
    text: "According to 14 CFR Part 121.481, what is the minimum rest period required between duty periods for flight crew members?",
    choices: [
      { key: "A", text: "8 consecutive hours" },
      { key: "B", text: "9 consecutive hours" },
      { key: "C", text: "10 consecutive hours" },
    ],
    correct: "B",
  },
  {
    id: "ATP0003",
    aok: "Weather",
    text: "At FL350, what is the approximate windshear alert threshold that should trigger evasive action in a jet transport aircraft?",
    choices: [
      { key: "A", text: "15 knots per 1000 feet" },
      { key: "B", text: "25 knots per 1000 feet" },
      { key: "C", text: "40 knots per 1000 feet" },
    ],
    correct: "C",
  },
  {
    id: "ATP0004",
    aok: "Weather",
    text: "Which phenomenon is most significant for high-altitude cruise operations above FL300?",
    choices: [
      { key: "A", text: "Clear air turbulence and jet streams" },
      { key: "B", text: "Microbursts and wind shear" },
      { key: "C", text: "Convective moisture and icing" },
    ],
    correct: "A",
  },
  {
    id: "ATP0005",
    aok: "Navigation and Flight Planning",
    text: "When planning an oceanic flight requiring CPDLC clearance, what is the minimum separation standard for aircraft at the same flight level?",
    choices: [
      { key: "A", text: "50 nautical miles longitudinal separation" },
      { key: "B", text: "80 nautical miles longitudinal separation" },
      { key: "C", text: "100 nautical miles longitudinal separation" },
    ],
    correct: "A",
  },
  {
    id: "ATP0006",
    aok: "Navigation and Flight Planning",
    text: "For an ETOPS-200 flight, what is the minimum two-engine cruise altitude requirement if one engine fails over the Pacific?",
    choices: [
      { key: "A", text: "FL350 or the MEA, whichever is higher" },
      { key: "B", text: "FL250 or the applicable minimum altitude, whichever is higher" },
      { key: "C", text: "FL280 or the MEA, whichever is higher" },
    ],
    correct: "A",
  },
  {
    id: "ATP0007",
    aok: "Performance and Limitations",
    text: "At maximum structural cruise weight, a Boeing 747 has a service ceiling of approximately:",
    choices: [
      { key: "A", text: "FL350" },
      { key: "B", text: "FL450" },
      { key: "C", text: "FL550" },
    ],
    correct: "B",
  },
  {
    id: "ATP0008",
    aok: "Performance and Limitations",
    text: "What factor has the greatest effect on the takeoff distance of a heavy jet aircraft operating from a hot, high-altitude airport?",
    choices: [
      { key: "A", text: "Air temperature" },
      { key: "B", text: "Runway surface friction" },
      { key: "C", text: "Density altitude" },
    ],
    correct: "C",
  },
  {
    id: "ATP0009",
    aok: "Aerodynamics",
    text: "At transonic speeds, the shock-induced separation on a swept wing primarily affects which flight characteristic?",
    choices: [
      { key: "A", text: "Pitch stability and trim change" },
      { key: "B", text: "Lateral stability and roll performance" },
      { key: "C", text: "Directional stability and yaw characteristics" },
    ],
    correct: "A",
  },
  {
    id: "ATP0010",
    aok: "Aerodynamics",
    text: "During approach with a failed engine on a twin-engine jet, which aerodynamic phenomenon becomes more critical at slow speeds?",
    choices: [
      { key: "A", text: "Wave drag and compressibility effects" },
      { key: "B", text: "Asymmetric thrust and adverse yaw" },
      { key: "C", text: "Ground effect and induced drag increase" },
    ],
    correct: "B",
  },
  {
    id: "ATP0011",
    aok: "Aircraft Systems",
    text: "In a modern high-bypass turbofan engine, what percentage of total thrust typically comes from the bypass air?",
    choices: [
      { key: "A", text: "30-40 percent" },
      { key: "B", text: "60-80 percent" },
      { key: "C", text: "80-90 percent" },
    ],
    correct: "C",
  },
  {
    id: "ATP0012",
    aok: "Aircraft Systems",
    text: "What is the primary function of RVSM (Reduced Vertical Separation Minima) capability approval?",
    choices: [
      { key: "A", text: "To reduce fuel burn by allowing lower cruising altitudes" },
      { key: "B", text: "To increase airspace capacity by allowing 1000-foot vertical separations between FL290-FL410" },
      { key: "C", text: "To improve navigation accuracy using GPS and INS integration" },
    ],
    correct: "B",
  },
  {
    id: "ATP0013",
    aok: "Crew Resource Management",
    text: "According to modern CRM principles, what is the primary responsibility of the Pilot Monitoring when the Pilot Flying declares a go-around?",
    choices: [
      { key: "A", text: "Prepare the landing gear for retraction and configure for climb" },
      { key: "B", text: "Announce the go-around and cross-check the flight path" },
      { key: "C", text: "Take control of the aircraft immediately" },
    ],
    correct: "B",
  },
  {
    id: "ATP0014",
    aok: "Crew Resource Management",
    text: "In a multi-crew environment, how should a crew member address a safety concern with the captain if they perceive a potential error?",
    choices: [
      { key: "A", text: "Wait until after landing to discuss the issue privately" },
      { key: "B", text: "Use a structured advocacy technique and clearly state the concern" },
      { key: "C", text: "Assume the captain is aware and monitor the situation" },
    ],
    correct: "B",
  },
  {
    id: "ATP0015",
    aok: "Emergency Procedures",
    text: "When both hydraulic systems fail in a jet transport, what is the primary method of flight control available?",
    choices: [
      { key: "A", text: "Stabilizer trim and manual control columns connected to ram air turbine" },
      { key: "B", text: "Emergency electrical system and backup hydraulic pump" },
      { key: "C", text: "Engine thrust differential and aerodynamic control surfaces" },
    ],
    correct: "A",
  },
  {
    id: "ATP0016",
    aok: "Emergency Procedures",
    text: "During an in-flight engine fire in a twin-engine jet, after immediately identifying and isolating the engine, what is the next critical action?",
    choices: [
      { key: "A", text: "Deploy the fire extinguisher and monitor engine temperatures" },
      { key: "B", text: "Declare an emergency and plan an immediate landing" },
      { key: "C", text: "Reduce power and monitor for fire indication changes before deciding landing strategy" },
    ],
    correct: "B",
  },
];
