// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const CAX_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const CAX_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "National Airspace System",
  "Weather",
  "Cross-Country Flight Planning",
  "Performance and Limitations",
  "Principles of Flight",
  "Aircraft Systems",
  "Flight Instruments",
  "Aeromedical Factors",
  "Commercial Operations",
] as const;

export const CAX_QUESTIONS: TestBankQuestion[] = [
  {
    id: "CAX0001",
    aok: "Regulations",
    text: "A commercial pilot is planning to conduct charter flights under Part 135. Which of the following is NOT required for the pilot in command?",
    choices: [
      { key: "A", text: "A commercial pilot certificate with an airplane single-engine land rating" },
      { key: "B", text: "Type rating for the aircraft if required by FAA" },
      { key: "C", text: "Completion of Initial Operating Experience (IOE) before acting as PIC" },
    ],
    correct: "C",
  },
  {
    id: "CAX0002",
    aok: "Regulations",
    text: "Under Part 119, what is the maximum number of flight hours a Part 135 pilot in command may conduct in a 7 consecutive day period without an additional pilot?",
    choices: [
      { key: "A", text: "120 hours" },
      { key: "B", text: "100 hours" },
      { key: "C", text: "90 hours" },
    ],
    correct: "C",
  },
  {
    id: "CAX0003",
    aok: "National Airspace System",
    text: "A commercial pilot is operating in Class B airspace. What is the minimum visibility requirement and required distance from clouds?",
    choices: [
      { key: "A", text: "3 statute miles visibility and clear of clouds" },
      { key: "B", text: "5 statute miles visibility and 1,000 feet below, 1,000 feet above, and 1 nautical mile horizontal from clouds" },
      { key: "C", text: "10 statute miles visibility and 1,000 feet separation from all clouds" },
    ],
    correct: "B",
  },
  {
    id: "CAX0004",
    aok: "National Airspace System",
    text: "Which service is provided by an ARTCC (Air Route Traffic Control Center) at flight levels above 18,000 feet?",
    choices: [
      { key: "A", text: "Runway incursion warnings and traffic advisories" },
      { key: "B", text: "Radar vectors for instrument approaches and separation services" },
      { key: "C", text: "Clearance delivery and initial contact frequencies" },
    ],
    correct: "B",
  },
  {
    id: "CAX0005",
    aok: "Weather",
    text: "A commercial pilot observes a thunderstorm with a flat top at about 35,000 feet MSL. What type of weather system is this characteristic of?",
    choices: [
      { key: "A", text: "Cumulus clouds reaching the tropopause" },
      { key: "B", text: "Moderate turbulence with light precipitation" },
      { key: "C", text: "A dissipating storm cell producing wind shear only" },
    ],
    correct: "A",
  },
  {
    id: "CAX0006",
    aok: "Weather",
    text: "What is the primary cause of wind shear at low altitude during the passage of a cold front?",
    choices: [
      { key: "A", text: "Temperature inversion creating density differential layers" },
      { key: "B", text: "Rapid change in wind direction and speed within a short vertical distance" },
      { key: "C", text: "Convective currents from uneven surface heating" },
    ],
    correct: "B",
  },
  {
    id: "CAX0007",
    aok: "Cross-Country Flight Planning",
    text: "A commercial pilot is planning a 500 nautical mile cross-country flight. The forecast indicates winds aloft at flight level 65 knots from 030 degrees with a true course of 090 degrees. What is the approximate groundspeed?",
    choices: [
      { key: "A", text: "125 knots" },
      { key: "B", text: "135 knots" },
      { key: "C", text: "155 knots" },
    ],
    correct: "A",
  },
  {
    id: "CAX0008",
    aok: "Cross-Country Flight Planning",
    text: "Which documents must be aboard an aircraft conducting a commercial flight operation?",
    choices: [
      { key: "A", text: "Certificate of airworthiness, weight and balance data, and aircraft maintenance records" },
      { key: "B", text: "Airworthiness certificate, POH/AFM, weight and balance data, and maintenance records not older than 12 months" },
      { key: "C", text: "Registration certificate, airworthiness certificate, POH/AFM, weight and balance, and current weight and balance records" },
    ],
    correct: "C",
  },
  {
    id: "CAX0009",
    aok: "Performance and Limitations",
    text: "An aircraft has a service ceiling of 25,000 feet. What is the definition of service ceiling?",
    choices: [
      { key: "A", text: "The maximum altitude at which the aircraft can maintain level flight" },
      { key: "B", text: "The maximum altitude at which the aircraft can maintain a rate of climb of 100 feet per minute" },
      { key: "C", text: "The altitude at which the aircraft reaches its maximum true airspeed" },
    ],
    correct: "B",
  },
  {
    id: "CAX0010",
    aok: "Performance and Limitations",
    text: "What effect does a 20-degree bank angle during a cruise climb have on the aircraft's rate of climb?",
    choices: [
      { key: "A", text: "Rate of climb increases by approximately 10 percent" },
      { key: "B", text: "Rate of climb decreases by approximately 5 to 10 percent" },
      { key: "C", text: "Rate of climb remains unchanged due to constant power settings" },
    ],
    correct: "B",
  },
  {
    id: "CAX0011",
    aok: "Principles of Flight",
    text: "During a chandelle maneuver, at what point is the bank angle at its maximum value?",
    choices: [
      { key: "A", text: "At the start of the maneuver when initiating the turn" },
      { key: "B", text: "Approximately 180 degrees through the turn at the highest point of the climb" },
      { key: "C", text: "At the completion of the 180-degree turn when returning to level flight" },
    ],
    correct: "B",
  },
  {
    id: "CAX0012",
    aok: "Principles of Flight",
    text: "What is the primary purpose of performing a lazy eight maneuver?",
    choices: [
      { key: "A", text: "To increase altitude while improving cruise efficiency" },
      { key: "B", text: "To develop orientation, coordination, and control techniques in three-dimensional flight" },
      { key: "C", text: "To maintain a specific heading while climbing at maximum rate" },
    ],
    correct: "B",
  },
  {
    id: "CAX0013",
    aok: "Aircraft Systems",
    text: "In a retractable gear aircraft, what is the normal procedure if the landing gear fails to extend before landing?",
    choices: [
      { key: "A", text: "Attempt to manually crank the gear and use forward slip if necessary" },
      { key: "B", text: "Reduce airspeed to approach speed, attempt manual extension, and consider belly landing" },
      { key: "C", text: "Increase airspeed to improve aerodynamic forces on the gear and attempt cycling" },
    ],
    correct: "B",
  },
  {
    id: "CAX0014",
    aok: "Aircraft Systems",
    text: "What is the function of the elevator trim system in a high-performance aircraft?",
    choices: [
      { key: "A", text: "To reduce the load on elevator control cables during flight" },
      { key: "B", text: "To maintain level flight at various airspeed and weight configurations without control pressure" },
      { key: "C", text: "To prevent flutter by aerodynamically balancing the tail surface" },
    ],
    correct: "B",
  },
  {
    id: "CAX0015",
    aok: "Flight Instruments",
    text: "What instrument malfunction is indicated by the attitude indicator showing continuous drift toward the horizon in one direction during straight-and-level flight?",
    choices: [
      { key: "A", text: "Precession error, which is normal and should be corrected periodically" },
      { key: "B", text: "A stuck or failing gyroscope requiring immediate instrument repair" },
      { key: "C", text: "Vacuum pump failure affecting all gyroscopic instruments equally" },
    ],
    correct: "A",
  },
  {
    id: "CAX0016",
    aok: "Flight Instruments",
    text: "When transitioning from visual flight to instrument meteorological conditions, what is the first indication that the aircraft has entered a cloud?",
    choices: [
      { key: "A", text: "The airspeed indicator shows a rapid increase in true airspeed" },
      { key: "B", text: "Forward visibility decreases and instrument cross-check becomes essential" },
      { key: "C", text: "The vertical speed indicator immediately shows a descent rate" },
    ],
    correct: "B",
  },
  {
    id: "CAX0017",
    aok: "Aeromedical Factors",
    text: "A commercial pilot reports experiencing slight tunnel vision and a sensation of well-being at 18,000 feet MSL without supplemental oxygen. What is the most likely physiological cause?",
    choices: [
      { key: "A", text: "Hyperoxia from increased atmospheric pressure" },
      { key: "B", text: "Hypoxia affecting cerebral function and judgment" },
      { key: "C", text: "Decompression sickness from rapid altitude gain" },
    ],
    correct: "B",
  },
  {
    id: "CAX0018",
    aok: "Aeromedical Factors",
    text: "What is the maximum cabin altitude at which a commercial pilot may conduct flight operations without being required to use supplemental oxygen?",
    choices: [
      { key: "A", text: "10,000 feet MSL for the pilot and 12,500 feet for passengers" },
      { key: "B", text: "14,000 feet MSL for all occupants" },
      { key: "C", text: "12,500 feet MSL for the pilot and 15,000 feet MSL for crew" },
    ],
    correct: "A",
  },
  {
    id: "CAX0019",
    aok: "Commercial Operations",
    text: "A commercial pilot is conducting an air tour operation in mountainous terrain. What is the minimum safe altitude above the highest obstacle within 5 statute miles of the flight path?",
    choices: [
      { key: "A", text: "500 feet above ground level" },
      { key: "B", text: "1,000 feet above ground level" },
      { key: "C", text: "2,000 feet above ground level" },
    ],
    correct: "C",
  },
  {
    id: "CAX0020",
    aok: "Commercial Operations",
    text: "Under what condition may a commercial pilot legally act as pilot in command while that pilot's medical certificate is invalid or not current?",
    choices: [
      { key: "A", text: "If the pilot holds a valid drivers license and the flight is not for compensation" },
      { key: "B", text: "Only if operating under the sport pilot exemption or with proper FAA authorization" },
      { key: "C", text: "A current medical certificate is always required for commercial operations" },
    ],
    correct: "C",
  },
];
