// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const FIA_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const FIA_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "National Airspace System",
  "Weather",
  "Flight Planning",
  "Performance and Limitations",
  "Principles of Flight",
  "Aircraft Systems",
  "Flight Instruments",
  "Aeromedical Factors",
  "Flight Instruction Techniques",
] as const;

export const FIA_QUESTIONS: TestBankQuestion[] = [
  {
    id: "FIA0001",
    aok: "Regulations",
    text: "What is the minimum amount of pilot-in-command experience required to act as a flight instructor?",
    choices: [
      { key: "A", text: "250 hours total flight time with 100 hours as pilot-in-command" },
      { key: "B", text: "500 hours total flight time with 100 hours cross-country and 50 hours in the category/class" },
      { key: "C", text: "250 hours of pilot-in-command flight time" },
    ],
    correct: "B",
  },
  {
    id: "FIA0002",
    aok: "Regulations",
    text: "A flight instructor may issue a solo endorsement for a student pilot if the student meets which requirement?",
    choices: [
      { key: "A", text: "Minimum of 15 hours of dual instruction in the aircraft category" },
      { key: "B", text: "Meets the appropriate aeronautical knowledge and flight proficiency standards" },
      { key: "C", text: "Has logged at least 10 hours of solo flight time in other aircraft" },
    ],
    correct: "B",
  },
  {
    id: "FIA0003",
    aok: "National Airspace System",
    text: "What minimum altitude is required when operating VFR in Class B airspace?",
    choices: [
      { key: "A", text: "Flight level 250 or below at specific altitudes assigned by ATC" },
      { key: "B", text: "500 feet above ground level" },
      { key: "C", text: "No specific altitude requirement if cleared by ATC" },
    ],
    correct: "A",
  },
  {
    id: "FIA0004",
    aok: "National Airspace System",
    text: "A student pilot is conducting a cross-country flight in Class D airspace. What are the requirements for entering the airspace?",
    choices: [
      { key: "A", text: "Student must have a third-class medical and 10 hours of cross-country experience" },
      { key: "B", text: "Student must receive a special endorsement from their instructor" },
      { key: "C", text: "Student must obtain clearance from the control tower before entering" },
    ],
    correct: "C",
  },
  {
    id: "FIA0005",
    aok: "Weather",
    text: "What is the primary purpose of teaching a student pilot about wind shear?",
    choices: [
      { key: "A", text: "To prepare them for high-altitude flying operations" },
      { key: "B", text: "To help them recognize sudden changes in wind speed and direction that can affect aircraft control" },
      { key: "C", text: "To understand how to calculate crosswind components for landing" },
    ],
    correct: "B",
  },
  {
    id: "FIA0006",
    aok: "Weather",
    text: "When teaching weather briefing interpretation, which phenomenon presents the most significant hazard during takeoff and landing?",
    choices: [
      { key: "A", text: "Clear air turbulence above 25,000 feet" },
      { key: "B", text: "Microbursts and wind shear" },
      { key: "C", text: "Virga and dry convection" },
    ],
    correct: "B",
  },
  {
    id: "FIA0007",
    aok: "Flight Planning",
    text: "When preparing a student for a cross-country flight, the instructor should ensure the flight plan accounts for which factors?",
    choices: [
      { key: "A", text: "Winds aloft, fuel requirements, alternate airports, and aircraft performance limitations" },
      { key: "B", text: "Only fuel and distance to destination" },
      { key: "C", text: "Runway length at destination and magnetic declination" },
    ],
    correct: "A",
  },
  {
    id: "FIA0008",
    aok: "Flight Planning",
    text: "What is the significance of calculating true airspeed when flight planning for a student's cross-country flight?",
    choices: [
      { key: "A", text: "It allows accurate calculation of ground speed, fuel burn, and arrival time" },
      { key: "B", text: "It is required by the FAA for all flights exceeding 50 nautical miles" },
      { key: "C", text: "It ensures compliance with airspace speed restrictions" },
    ],
    correct: "A",
  },
  {
    id: "FIA0009",
    aok: "Performance and Limitations",
    text: "A student pilot asks why the aircraft's takeoff distance increases significantly on a hot, high-altitude day. What is the best explanation?",
    choices: [
      { key: "A", text: "The engine produces less power due to thinner air and higher temperature reducing air density" },
      { key: "B", text: "The propeller pitch increases automatically on hot days" },
      { key: "C", text: "Weight and balance limitations prevent heavier loads on hot days" },
    ],
    correct: "A",
  },
  {
    id: "FIA0010",
    aok: "Performance and Limitations",
    text: "When teaching the effects of loading on aircraft performance, an instructor should emphasize that exceeding the center of gravity envelope can result in what primary hazard?",
    choices: [
      { key: "A", text: "Increased fuel consumption and range reduction" },
      { key: "B", text: "Loss of control authority and unrecoverable stalls or spins" },
      { key: "C", text: "Excessive engine vibration during cruise flight" },
    ],
    correct: "B",
  },
  {
    id: "FIA0011",
    aok: "Principles of Flight",
    text: "When teaching the concept of lift, which statement best explains why an airfoil generates lift?",
    choices: [
      { key: "A", text: "Increased air pressure on the bottom surface pushes the wing up" },
      { key: "B", text: "Faster-moving air over the curved upper surface creates lower pressure relative to the lower surface" },
      { key: "C", text: "The angle of attack creates equal pressure differential across the entire wing" },
    ],
    correct: "B",
  },
  {
    id: "FIA0012",
    aok: "Principles of Flight",
    text: "A student asks why the aircraft will enter an accelerated stall if back pressure is applied rapidly during a climbing turn. The instructor should explain that:",
    choices: [
      { key: "A", text: "The load factor increases, requiring higher airspeed to maintain lift without stalling" },
      { key: "B", text: "The engine cannot provide enough power to maintain altitude while climbing" },
      { key: "C", text: "The angle of attack remains constant regardless of bank angle in a turn" },
    ],
    correct: "A",
  },
  {
    id: "FIA0013",
    aok: "Aircraft Systems",
    text: "During the preflight briefing, an instructor notices the student is unfamiliar with the purpose of the vacuum system. What is the primary function an instructor should emphasize?",
    choices: [
      { key: "A", text: "It provides air circulation to cool the engine during cruise flight" },
      { key: "B", text: "It powers essential flight instruments such as the attitude indicator and directional gyro" },
      { key: "C", text: "It operates the cabin pressurization system at high altitudes" },
    ],
    correct: "B",
  },
  {
    id: "FIA0014",
    aok: "Aircraft Systems",
    text: "An instructor is teaching a student about the electrical system. Which of the following is the primary function of the alternator in the aircraft electrical system?",
    choices: [
      { key: "A", text: "It stores electrical energy for engine starting" },
      { key: "B", text: "It provides electrical power to all aircraft systems during flight and recharges the battery" },
      { key: "C", text: "It regulates alternating current to direct current for the avionics" },
    ],
    correct: "B",
  },
  {
    id: "FIA0015",
    aok: "Flight Instruments",
    text: "When teaching instrument flying, an instructor should stress the importance of the attitude indicator because:",
    choices: [
      { key: "A", text: "It is the only instrument that provides reliable pitch and bank information" },
      { key: "B", text: "It is immune to errors from slips, skids, and acceleration" },
      { key: "C", text: "It directly measures angle of attack throughout the flight envelope" },
    ],
    correct: "A",
  },
  {
    id: "FIA0016",
    aok: "Flight Instruments",
    text: "A student misinterprets the turn coordinator during a coordinated turn. The instructor should clarify that the instrument shows:",
    choices: [
      { key: "A", text: "Rate and direction of turn, with a secondary indication of slip or skid" },
      { key: "B", text: "Bank angle and rate of altitude change" },
      { key: "C", text: "Heading and magnetic deviation" },
    ],
    correct: "A",
  },
  {
    id: "FIA0017",
    aok: "Aeromedical Factors",
    text: "When teaching a student about hypoxia, which altitude typically presents the first noticeable effects for an unpressurized aircraft?",
    choices: [
      { key: "A", text: "5,000 feet mean sea level" },
      { key: "B", text: "8,000 to 10,000 feet mean sea level" },
      { key: "C", text: "15,000 feet mean sea level" },
    ],
    correct: "B",
  },
  {
    id: "FIA0018",
    aok: "Aeromedical Factors",
    text: "An instructor should teach students about spatial disorientation because it is:",
    choices: [
      { key: "A", text: "A temporary condition that only occurs in low-visibility conditions" },
      { key: "B", text: "A dangerous condition where the pilot's sensory systems conflict with instrument indications" },
      { key: "C", text: "Easily corrected by increasing airspeed and descent rate" },
    ],
    correct: "B",
  },
  {
    id: "FIA0019",
    aok: "Flight Instruction Techniques",
    text: "The most effective method for teaching a student to recover from an unusual attitude is:",
    choices: [
      { key: "A", text: "Explaining the procedures in the classroom before any actual flight practice" },
      { key: "B", text: "Demonstrating the recovery technique, then allowing the student to practice under controlled conditions" },
      { key: "C", text: "Assigning the student to read the aircraft manual and then test knowledge with a quiz" },
    ],
    correct: "B",
  },
  {
    id: "FIA0020",
    aok: "Flight Instruction Techniques",
    text: "When a student demonstrates a persistent error in coordinating aileron and rudder during a turn, the instructor should:",
    choices: [
      { key: "A", text: "Immediately correct the error and demonstrate the proper technique" },
      { key: "B", text: "Allow the student to continue until they recognize the error, then guide them toward the solution" },
      { key: "C", text: "Reduce the complexity by simplifying the maneuver until the student masters each component" },
    ],
    correct: "C",
  },
];
