// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const FII_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const FII_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "Flight Instruments",
  "Navigation and Flight Planning",
  "Weather",
  "IFR Procedures",
  "ATC Procedures",
  "Instructional Knowledge",
] as const;

export const FII_QUESTIONS: TestBankQuestion[] = [
  {
    id: "FII0001",
    aok: "Regulations",
    text: "What are the minimum aircraft equipment requirements for conducting an instrument training flight under 14 CFR Part 61?",
    choices: [
      { key: "A", text: "Aircraft must have a functioning attitude indicator, heading indicator, and airspeed indicator" },
      { key: "B", text: "Aircraft must have all instruments required by 14 CFR 91.205 plus operational pitot/static system and a functioning vacuum or pressure system" },
      { key: "C", text: "Aircraft must be equipped with an autopilot and dual navigation receivers" },
    ],
    correct: "B",
  },
  {
    id: "FII0002",
    aok: "Regulations",
    text: "Under 14 CFR Part 61, what minimum flight time is required to conduct instrument flight instruction in an aircraft?",
    choices: [
      { key: "A", text: "The instructor must have logged at least 50 hours of flight time in the category and class of aircraft used" },
      { key: "B", text: "The instructor must have logged at least 100 hours of pilot-in-command flight time in the category, class, or type of aircraft being used" },
      { key: "C", text: "The instructor must have at least 200 total hours of flight experience with no minimum in the specific aircraft" },
    ],
    correct: "B",
  },
  {
    id: "FII0003",
    aok: "Flight Instruments",
    text: "When teaching an instrument student to identify a vacuum system failure, which instrument would be the first to indicate the problem?",
    choices: [
      { key: "A", text: "The airspeed indicator, which would fluctuate between high and low readings" },
      { key: "B", text: "The attitude indicator, which would begin to precess and eventually tumble" },
      { key: "C", text: "The heading indicator, which would show erratic movement before the attitude indicator fails" },
    ],
    correct: "B",
  },
  {
    id: "FII0004",
    aok: "Flight Instruments",
    text: "How should an instructor teach proper instrument cross-check technique during straight and level flight?",
    choices: [
      { key: "A", text: "Focus primarily on the attitude indicator, checking airspeed and altitude every 10 seconds" },
      { key: "B", text: "Establish a systematic scan that includes the attitude indicator for pitch, heading indicator for bank, and airspeed/altimeter for performance parameters" },
      { key: "C", text: "Divide attention equally among all six instruments with no specific sequence required" },
    ],
    correct: "B",
  },
  {
    id: "FII0005",
    aok: "Navigation and Flight Planning",
    text: "When instructing a student on holding pattern entry procedures, which entry method is considered the most reliable for teaching purposes?",
    choices: [
      { key: "A", text: "Direct entry, as it requires no timing or distance calculations" },
      { key: "B", text: "The standard holding pattern entry based on the aircraft's magnetic heading relative to the inbound course" },
      { key: "C", text: "Only parallel or teardrop entries, as direct entry is too dangerous for training" },
    ],
    correct: "B",
  },
  {
    id: "FII0006",
    aok: "Navigation and Flight Planning",
    text: "How should an instructor teach a student to correct for wind in instrument approaches using ground-based navigation aids?",
    choices: [
      { key: "A", text: "Reduce throttle by 50% to slow descent rate and allow more time to identify wind correction needs" },
      { key: "B", text: "Maintain the published approach course through continuous small heading adjustments while monitoring localizer or VOR needle positioning" },
      { key: "C", text: "Establish a crab angle before starting descent and maintain it without further adjustment" },
    ],
    correct: "B",
  },
  {
    id: "FII0007",
    aok: "Weather",
    text: "An instrument student encounters moderate rime ice while in clouds. What should the instructor teach regarding the characteristics and danger of this condition?",
    choices: [
      { key: "A", text: "Rime ice is clear and hard to see on the windscreen, but has minimal aerodynamic effects on the airframe" },
      { key: "B", text: "Rime ice forms when supercooled water droplets freeze upon impact; it can significantly degrade aerodynamic efficiency and is challenging to remove through standard deicing equipment" },
      { key: "C", text: "Rime ice is the most dangerous form of aircraft icing and cannot be recovered from without immediately descending to warmer air" },
    ],
    correct: "B",
  },
  {
    id: "FII0008",
    aok: "Weather",
    text: "When teaching weather interpretation for instrument flight, how should an instructor explain the relationship between a reported SIGMET and an AIRMET?",
    choices: [
      { key: "A", text: "SIGMETs report significant weather phenomena affecting flight operations, while AIRMETs report hazards primarily of concern to lighter aircraft" },
      { key: "B", text: "Both report the same weather phenomena but SIGMETs are issued by controllers while AIRMETs are issued by pilots" },
      { key: "C", text: "AIRMETs are upgraded SIGMETs indicating more severe conditions" },
    ],
    correct: "A",
  },
  {
    id: "FII0009",
    aok: "IFR Procedures",
    text: "How should an instructor teach an instrument student to recover from an unusual attitude when instruments are unreliable or unavailable?",
    choices: [
      { key: "A", text: "Level the wings using outside visual references, then pitch the nose to the horizon" },
      { key: "B", text: "Pitch the nose level using the attitude indicator without relying on outside references, then adjust power and trim as needed" },
      { key: "C", text: "Reduce throttle to descent power and lower the landing gear to reduce aircraft performance until visual references are available" },
    ],
    correct: "B",
  },
  {
    id: "FII0010",
    aok: "IFR Procedures",
    text: "What teaching technique should an instructor use to help a student understand partial panel instrument flying in the event of an attitude indicator failure?",
    choices: [
      { key: "A", text: "Cover the attitude indicator and teach the student to use pitch, bank, and power relationships to control the aircraft using primary and secondary instruments" },
      { key: "B", text: "Immediately return to visual flight rules and land to avoid instrument errors" },
      { key: "C", text: "Have the student rely solely on the heading indicator and altimeter while avoiding all turns" },
    ],
    correct: "A",
  },
  {
    id: "FII0011",
    aok: "ATC Procedures",
    text: "An instrument student receives a clearance to '...descend and maintain 3,000, reduce speed to 250 knots.' How should the instructor explain the priority of complying with these instructions?",
    choices: [
      { key: "A", text: "Reduce speed first to ensure safe descent planning before altitude changes" },
      { key: "B", text: "Descend first to maintain obstacle clearance, then reduce speed once level at 3,000 feet" },
      { key: "C", text: "Both altitude and speed changes are equally important and should be initiated simultaneously using coordinated pitch and power adjustments" },
    ],
    correct: "B",
  },
  {
    id: "FII0012",
    aok: "ATC Procedures",
    text: "When instructing on instrument clearance readback procedures, what critical element should always be included to prevent misunderstandings?",
    choices: [
      { key: "A", text: "The aircraft call sign should be included in the readback along with the clearance items that have conditions or limitations" },
      { key: "B", text: "Only the heading and altitude need to be read back; other information is understood by context" },
      { key: "C", text: "Full readback of every word spoken by ATC, including aircraft identification and the controller's call sign" },
    ],
    correct: "A",
  },
  {
    id: "FII0013",
    aok: "Instructional Knowledge",
    text: "How should an instructor structure the teaching progression when introducing instrument approach procedure instruction?",
    choices: [
      { key: "A", text: "Immediately practice full approaches under the hood to build proficiency quickly" },
      { key: "B", text: "Begin with ground briefing of approach charts and procedures, then conduct a visual approach to teach the geography, then progress to actual instrument approaches" },
      { key: "C", text: "Have the student study the approach plate at home, then conduct multiple full instrument approaches without any familiarization flight" },
    ],
    correct: "B",
  },
  {
    id: "FII0014",
    aok: "Instructional Knowledge",
    text: "What is the most effective way to assess whether an instrument student has truly mastered instrument scan technique versus simply going through the motions?",
    choices: [
      { key: "A", text: "Ask the student to verbally describe instrument references while you create instrument failures or unusual instrument presentations to evaluate response timing" },
      { key: "B", text: "Observe the student's eyes during flight and count how many times they look at the attitude indicator" },
      { key: "C", text: "Give the student a written test on instrument relationships and scanning priorities" },
    ],
    correct: "A",
  },
];
