// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const FOI_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const FOI_AREAS_OF_KNOWLEDGE = [
  "The Learning Process",
  "Human Behavior and Communication",
  "The Teaching Process",
  "Assessment and Critique",
  "Instructor Responsibilities",
  "Techniques of Flight Instruction",
] as const;

export const FOI_QUESTIONS: TestBankQuestion[] = [
  {
    id: "FOI0001",
    aok: "The Learning Process",
    text: "Which level of learning is described as the ability to apply a procedure to a new situation?",
    choices: [
      { key: "A", text: "Rote learning" },
      { key: "B", text: "Application" },
      { key: "C", text: "Correlation" },
    ],
    correct: "B",
  },
  {
    id: "FOI0002",
    aok: "The Learning Process",
    text: "What is the primary purpose of assessment during flight instruction?",
    choices: [
      { key: "A", text: "To provide feedback and identify areas for improvement" },
      { key: "B", text: "To determine if the student can be hired as a pilot" },
      { key: "C", text: "To ensure the flight school meets insurance requirements" },
    ],
    correct: "A",
  },
  {
    id: "FOI0003",
    aok: "Human Behavior and Communication",
    text: "A student pilot becomes defensive when corrected on a landing error. This response is best described as:",
    choices: [
      { key: "A", text: "A defense mechanism to protect self-esteem" },
      { key: "B", text: "A sign the student is not capable of learning to fly" },
      { key: "C", text: "An indication of poor aircraft handling ability" },
    ],
    correct: "A",
  },
  {
    id: "FOI0004",
    aok: "Human Behavior and Communication",
    text: "Which communication technique is most effective when explaining a complex maneuver to a student?",
    choices: [
      { key: "A", text: "Using technical jargon to establish credibility" },
      { key: "B", text: "Breaking the concept into small, understandable parts" },
      { key: "C", text: "Providing the explanation only once to test student attention" },
    ],
    correct: "B",
  },
  {
    id: "FOI0005",
    aok: "The Teaching Process",
    text: "The four-step method of instruction includes preparation, presentation, application, and:",
    choices: [
      { key: "A", text: "Assessment" },
      { key: "B", text: "Review" },
      { key: "C", text: "Evaluation" },
    ],
    correct: "B",
  },
  {
    id: "FOI0006",
    aok: "The Teaching Process",
    text: "What is the primary objective of a lesson plan in flight instruction?",
    choices: [
      { key: "A", text: "To provide a structured framework for organized, effective instruction" },
      { key: "B", text: "To satisfy regulatory requirements for documentation" },
      { key: "C", text: "To ensure the instructor appears professional to the student" },
    ],
    correct: "A",
  },
  {
    id: "FOI0007",
    aok: "Assessment and Critique",
    text: "An instructor providing constructive critique should focus on:",
    choices: [
      { key: "A", text: "The student's personal characteristics and attitude" },
      { key: "B", text: "Specific areas needing improvement with suggestions for better performance" },
      { key: "C", text: "Comparing the student's performance to other students" },
    ],
    correct: "B",
  },
  {
    id: "FOI0008",
    aok: "Assessment and Critique",
    text: "When critiquing a student's performance, the instructor should:",
    choices: [
      { key: "A", text: "Wait until after the flight to provide all feedback at once" },
      { key: "B", text: "Provide feedback immediately when safe to do so and also after the flight" },
      { key: "C", text: "Never criticize during flight to maintain student confidence" },
    ],
    correct: "B",
  },
  {
    id: "FOI0009",
    aok: "Instructor Responsibilities",
    text: "An instructor's primary responsibility regarding Aeronautical Decision Making (ADM) is to:",
    choices: [
      { key: "A", text: "Make all decisions for the student pilot during training flights" },
      { key: "B", text: "Teach students to recognize risks and make sound decisions" },
      { key: "C", text: "Ensure the student memorizes the FAA decision-making process" },
    ],
    correct: "B",
  },
  {
    id: "FOI0010",
    aok: "Instructor Responsibilities",
    text: "Which of the following is NOT a responsibility of the flight instructor?",
    choices: [
      { key: "A", text: "Providing quality flight instruction and positive role modeling" },
      { key: "B", text: "Determining student certification eligibility" },
      { key: "C", text: "Signing logbooks to document the student's achievement" },
    ],
    correct: "B",
  },
  {
    id: "FOI0011",
    aok: "Techniques of Flight Instruction",
    text: "The FITS acronym in flight instruction stands for:",
    choices: [
      { key: "A", text: "Flying Instrument Training System" },
      { key: "B", text: "Fundamentals of Instructing Training Standards" },
      { key: "C", text: "Focused Instruction Training and Scenarios" },
    ],
    correct: "C",
  },
  {
    id: "FOI0012",
    aok: "Techniques of Flight Instruction",
    text: "Which technique allows a student to learn by actually performing the maneuver with instructor guidance?",
    choices: [
      { key: "A", text: "Demonstration" },
      { key: "B", text: "Lecture" },
      { key: "C", text: "Guided practice" },
    ],
    correct: "C",
  },
];
