// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const IRA_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const IRA_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "Flight Instruments",
  "Navigation and Flight Planning",
  "Weather",
  "IFR Procedures",
  "ATC Procedures",
  "Emergency Procedures",
] as const;

export const IRA_QUESTIONS: TestBankQuestion[] = [
  {
    id: "IRA0001",
    aok: "Regulations",
    text: "What are the currency requirements for operating an aircraft under IFR? A pilot must have completed at least how many instrument approaches within the preceding 6 calendar months?",
    choices: [
      { key: "A", text: "3 instrument approaches with an authorized instructor" },
      { key: "B", text: "6 instrument approaches or 6 instrument approaches with an authorized instructor" },
      { key: "C", text: "6 instrument approaches in actual IFR conditions" },
    ],
    correct: "B",
  },
  {
    id: "IRA0002",
    aok: "Regulations",
    text: "An aircraft operated under IFR must be equipped with which of the following?",
    choices: [
      { key: "A", text: "Dual VOR receivers, DME, and an approved autopilot system" },
      { key: "B", text: "Two-way radio communications equipment, suitable instruments and equipment for the IFR flight to be executed, and instruments and equipment that meet the minimum certification standards" },
      { key: "C", text: "An ILS receiver, dual altitude reporting transponder, and a certified GPS unit" },
    ],
    correct: "B",
  },
  {
    id: "IRA0003",
    aok: "Flight Instruments",
    text: "What is the primary function of the attitude indicator in an IFR aircraft?",
    choices: [
      { key: "A", text: "To indicate the aircraft's pitch and bank attitude relative to the artificial horizon" },
      { key: "B", text: "To measure the rate of descent or ascent of the aircraft" },
      { key: "C", text: "To provide directional information for navigation purposes" },
    ],
    correct: "A",
  },
  {
    id: "IRA0004",
    aok: "Flight Instruments",
    text: "If a vacuum-powered attitude indicator fails in actual instrument conditions, what action should be taken immediately?",
    choices: [
      { key: "A", text: "Switch to the standby vacuum system and declare an emergency" },
      { key: "B", text: "Request immediate descent to VFR conditions and declare an emergency" },
      { key: "C", text: "Reference the turn coordinator and heading indicator as primary attitude reference instruments" },
    ],
    correct: "C",
  },
  {
    id: "IRA0005",
    aok: "Navigation and Flight Planning",
    text: "When tracking outbound on a VOR radial, a pilot experiences left needle deviation. What corrective action is appropriate?",
    choices: [
      { key: "A", text: "Turn left to intercept the radial" },
      { key: "B", text: "Turn right to intercept the radial" },
      { key: "C", text: "Turn to maintain the same radial" },
    ],
    correct: "B",
  },
  {
    id: "IRA0006",
    aok: "Navigation and Flight Planning",
    text: "What is the maximum holding pattern speed for aircraft at or below 6,000 feet MSL?",
    choices: [
      { key: "A", text: "160 knots true airspeed" },
      { key: "B", text: "200 knots indicated airspeed" },
      { key: "C", text: "250 knots indicated airspeed" },
    ],
    correct: "B",
  },
  {
    id: "IRA0007",
    aok: "Weather",
    text: "What is the minimum IFR weather requirement for conducting an instrument approach when the ceiling is 200 feet AGL and visibility is 1/2 statute mile?",
    choices: [
      { key: "A", text: "These conditions are below minimums and approach cannot be initiated" },
      { key: "B", text: "Approach can be initiated; descent below minimums is not authorized" },
      { key: "C", text: "Approach can be initiated only in an aircraft with a functioning autopilot" },
    ],
    correct: "B",
  },
  {
    id: "IRA0008",
    aok: "Weather",
    text: "Which type of icing is most dangerous for aircraft operations?",
    choices: [
      { key: "A", text: "Rime icing, which forms slowly and can be easily removed" },
      { key: "B", text: "Clear icing, which forms rapidly and is difficult to remove due to its density" },
      { key: "C", text: "Frost accumulation, which increases weight significantly" },
    ],
    correct: "B",
  },
  {
    id: "IRA0009",
    aok: "IFR Procedures",
    text: "When intercepting an ILS approach, what should be the standard descent rate when reaching the glideslope?",
    choices: [
      { key: "A", text: "1,000 feet per minute or less" },
      { key: "B", text: "Descent rate should not exceed 3 times the altitude of the glideslope intercept in feet per minute" },
      { key: "C", text: "500 feet per minute or less" },
    ],
    correct: "B",
  },
  {
    id: "IRA0010",
    aok: "IFR Procedures",
    text: "What action is required upon receiving a clearance limit and no further clearance is received?",
    choices: [
      { key: "A", text: "Hold at the clearance limit at the assigned altitude" },
      { key: "B", text: "Proceed to the clearance limit and begin a descent to VFR conditions" },
      { key: "C", text: "Begin descending to the minimum safe altitude and orbit" },
    ],
    correct: "A",
  },
  {
    id: "IRA0011",
    aok: "ATC Procedures",
    text: "When experiencing a lost communications emergency in IFR conditions, what transponder code should be set after establishing two-way radio contact is impossible?",
    choices: [
      { key: "A", text: "7777" },
      { key: "B", text: "7700" },
      { key: "C", text: "7600" },
    ],
    correct: "C",
  },
  {
    id: "IRA0012",
    aok: "ATC Procedures",
    text: "When assigned a 'radar vector,' what is the pilot's responsibility?",
    choices: [
      { key: "A", text: "Follow the heading provided and maintain altitude and airspeed as instructed" },
      { key: "B", text: "Follow the heading and make independent altitude changes as needed" },
      { key: "C", text: "Decline the vector and request a direct flight plan" },
    ],
    correct: "A",
  },
  {
    id: "IRA0013",
    aok: "Emergency Procedures",
    text: "If the vacuum system fails while executing an ILS approach in low ceiling/low visibility conditions, what is the proper action?",
    choices: [
      { key: "A", text: "Continue the approach using the standby instruments" },
      { key: "B", text: "Immediately execute a missed approach and declare an emergency" },
      { key: "C", text: "Switch to the backup electric attitude indicator and continue descent" },
    ],
    correct: "B",
  },
  {
    id: "IRA0014",
    aok: "Emergency Procedures",
    text: "In the event of complete electrical failure in IMC conditions, what instrument(s) remain reliable for attitude reference?",
    choices: [
      { key: "A", text: "The turn coordinator (if vacuum-powered) and the magnetic compass" },
      { key: "B", text: "Only the magnetic compass is reliable" },
      { key: "C", text: "The artificial horizon and the altitude indicator" },
    ],
    correct: "A",
  },
];
