// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const MEA_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const MEA_AREAS_OF_KNOWLEDGE = [
  "Multi-Engine Aerodynamics",
  "Engine-Out Procedures",
  "Performance and Limitations",
  "Systems",
  "Weight and Balance",
  "Emergency Procedures",
] as const;

export const MEA_QUESTIONS: TestBankQuestion[] = [
  {
    id: "MEA0001",
    aok: "Multi-Engine Aerodynamics",
    text: "What is Vmc (minimum control airspeed) in a multi-engine airplane?",
    choices: [
      { key: "A", text: "The minimum airspeed at which the airplane can be controlled with one engine inoperative and the critical engine windmilling." },
      { key: "B", text: "The speed at which the vertical stabilizer can no longer overcome asymmetric thrust." },
      { key: "C", text: "The never-exceed speed when operating on a single engine." },
    ],
    correct: "A",
  },
  {
    id: "MEA0002",
    aok: "Multi-Engine Aerodynamics",
    text: "Which engine is typically considered the critical engine on a conventional multi-engine airplane?",
    choices: [
      { key: "A", text: "The right engine, because it provides better single-engine performance." },
      { key: "B", text: "The left engine, because its failure produces the greatest yawing moment." },
      { key: "C", text: "Either engine; they are equally critical." },
    ],
    correct: "B",
  },
  {
    id: "MEA0003",
    aok: "Engine-Out Procedures",
    text: "How should a pilot identify which engine has failed immediately after an engine failure in flight?",
    choices: [
      { key: "A", text: "Look at engine temperature and pressure gauges to find the failed engine." },
      { key: "B", text: "Apply rudder pressure and observe which wing drops; the dead engine is on the side that drops." },
      { key: "C", text: "Check engine power settings and fuel flow to determine which engine is not producing power." },
    ],
    correct: "B",
  },
  {
    id: "MEA0004",
    aok: "Engine-Out Procedures",
    text: "When feathering a propeller after an engine failure, what is the primary purpose?",
    choices: [
      { key: "A", text: "To increase the remaining engine's power output." },
      { key: "B", text: "To minimize drag by aligning the propeller blades with the airflow." },
      { key: "C", text: "To prevent the windmilling propeller from damaging the engine." },
    ],
    correct: "B",
  },
  {
    id: "MEA0005",
    aok: "Performance and Limitations",
    text: "What does Vyse (best rate-of-climb speed with one engine inoperative) represent?",
    choices: [
      { key: "A", text: "The speed at which the airplane achieves the greatest altitude gain per unit of time on one engine." },
      { key: "B", text: "The maximum airspeed for safe single-engine operation." },
      { key: "C", text: "The speed at which the airplane can sustain level flight on one engine." },
    ],
    correct: "A",
  },
  {
    id: "MEA0006",
    aok: "Performance and Limitations",
    text: "Accelerate-stop distance in a multi-engine airplane is primarily used to determine what?",
    choices: [
      { key: "A", text: "The maximum distance required to stop the airplane from takeoff power on one engine." },
      { key: "B", text: "The distance needed to accelerate from takeoff to single-engine climb-out altitude." },
      { key: "C", text: "The runway length required to takeoff safely and reach decision speed before an engine fails." },
    ],
    correct: "A",
  },
  {
    id: "MEA0007",
    aok: "Systems",
    text: "Why are counter-rotating propellers used on some multi-engine airplanes?",
    choices: [
      { key: "A", text: "To increase the maximum power output of each engine." },
      { key: "B", text: "To eliminate or reduce the asymmetric thrust problem caused by a single critical engine." },
      { key: "C", text: "To improve fuel efficiency during multi-engine cruise operations." },
    ],
    correct: "B",
  },
  {
    id: "MEA0008",
    aok: "Systems",
    text: "What is asymmetric thrust, and when does it become a critical concern?",
    choices: [
      { key: "A", text: "Unequal thrust from each engine; it becomes critical during single-engine operation at low airspeeds." },
      { key: "B", text: "The difference in engine RPM settings; it affects fuel consumption during cruise." },
      { key: "C", text: "Higher thrust from the left engine due to P-factor; it only affects right-turning tendency." },
    ],
    correct: "A",
  },
  {
    id: "MEA0009",
    aok: "Weight and Balance",
    text: "How does the center of gravity location affect Vmc in a multi-engine airplane?",
    choices: [
      { key: "A", text: "An aft CG increases Vmc because less rudder authority is available." },
      { key: "B", text: "A forward CG decreases Vmc because more rudder authority is available." },
      { key: "C", text: "CG location has no effect on Vmc; it is determined only by wing geometry and engine power." },
    ],
    correct: "B",
  },
  {
    id: "MEA0010",
    aok: "Weight and Balance",
    text: "Which weight change would most significantly increase the single-engine climb performance of a multi-engine airplane?",
    choices: [
      { key: "A", text: "Increasing fuel load to ensure adequate range." },
      { key: "B", text: "Reducing aircraft weight by removing unnecessary equipment and ballast." },
      { key: "C", text: "Moving the center of gravity forward within limits." },
    ],
    correct: "B",
  },
  {
    id: "MEA0011",
    aok: "Emergency Procedures",
    text: "If an engine fails during takeoff below decision speed (V1), what action should the pilot take?",
    choices: [
      { key: "A", text: "Apply full rudder and attempt to maintain takeoff with one engine." },
      { key: "B", text: "Reject the takeoff and land on the remaining runway." },
      { key: "C", text: "Feather the propeller and continue with the remaining engine." },
    ],
    correct: "B",
  },
  {
    id: "MEA0012",
    aok: "Emergency Procedures",
    text: "What is the correct procedure if the landing gear fails to extend on a multi-engine airplane?",
    choices: [
      { key: "A", text: "Immediately declare an emergency and attempt an emergency landing." },
      { key: "B", text: "Cycle the landing gear several times and perform all applicable emergency procedures before landing." },
      { key: "C", text: "Increase engine power and maintain altitude until fuel is low, then attempt a forced landing." },
    ],
    correct: "B",
  },
];
