// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const RPA_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const RPA_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "National Airspace System",
  "Weather",
  "Performance and Limitations",
  "Principles of Flight",
  "Aircraft Systems",
  "Flight Instruments",
  "Aeromedical Factors",
] as const;

export const RPA_QUESTIONS: TestBankQuestion[] = [
  {
    id: "RPA0001",
    aok: "Regulations",
    text: "A recreational pilot may not operate an aircraft carrying more than how many occupants?",
    choices: [
      { key: "A", text: "2 occupants total, including the pilot" },
      { key: "B", text: "3 occupants total, including the pilot" },
      { key: "C", text: "4 occupants total, including the pilot" },
    ],
    correct: "B",
  },
  {
    id: "RPA0002",
    aok: "Regulations",
    text: "What is the maximum distance a recreational pilot may operate from the point of departure?",
    choices: [
      { key: "A", text: "25 nautical miles" },
      { key: "B", text: "50 nautical miles" },
      { key: "C", text: "100 nautical miles" },
    ],
    correct: "B",
  },
  {
    id: "RPA0003",
    aok: "National Airspace System",
    text: "Which airspace class requires a recreational pilot to establish two-way radio communication with ATC?",
    choices: [
      { key: "A", text: "Class E airspace" },
      { key: "B", text: "Class C airspace" },
      { key: "C", text: "Class G airspace" },
    ],
    correct: "B",
  },
  {
    id: "RPA0004",
    aok: "National Airspace System",
    text: "A recreational pilot flying in Class D airspace must maintain a minimum altitude awareness of:",
    choices: [
      { key: "A", text: "1,000 feet above ground level" },
      { key: "B", text: "1,200 feet above ground level" },
      { key: "C", text: "500 feet above ground level" },
    ],
    correct: "A",
  },
  {
    id: "RPA0005",
    aok: "Weather",
    text: "What is the minimum flight visibility required for a recreational pilot to operate in Class G airspace during the day?",
    choices: [
      { key: "A", text: "1 statute mile" },
      { key: "B", text: "3 statute miles" },
      { key: "C", text: "5 statute miles" },
    ],
    correct: "B",
  },
  {
    id: "RPA0006",
    aok: "Weather",
    text: "A recreational pilot encounters a ceiling of 700 feet with 2 statute miles visibility. What action should be taken?",
    choices: [
      { key: "A", text: "Continue—this meets VFR requirements" },
      { key: "B", text: "Divert—this is below VFR minimums" },
      { key: "C", text: "Climb above the layer immediately" },
    ],
    correct: "B",
  },
  {
    id: "RPA0007",
    aok: "Performance and Limitations",
    text: "Which type of engine failure is most critical for a recreational pilot flying a single-engine aircraft?",
    choices: [
      { key: "A", text: "Partial power loss in cruise" },
      { key: "B", text: "Complete engine failure immediately after takeoff" },
      { key: "C", text: "Intermittent engine roughness" },
    ],
    correct: "B",
  },
  {
    id: "RPA0008",
    aok: "Performance and Limitations",
    text: "A recreational pilot is planning a flight with a calculated range of 120 nautical miles. What is the maximum distance from the airport?",
    choices: [
      { key: "A", text: "50 nautical miles" },
      { key: "B", text: "60 nautical miles" },
      { key: "C", text: "80 nautical miles" },
    ],
    correct: "A",
  },
  {
    id: "RPA0009",
    aok: "Principles of Flight",
    text: "What effect does an increase in angle of attack have on the coefficient of lift?",
    choices: [
      { key: "A", text: "Decreases the coefficient of lift" },
      { key: "B", text: "Increases the coefficient of lift until stall" },
      { key: "C", text: "Has no effect on the coefficient of lift" },
    ],
    correct: "B",
  },
  {
    id: "RPA0010",
    aok: "Principles of Flight",
    text: "During a level turn, what must be true about lift to maintain altitude?",
    choices: [
      { key: "A", text: "Lift must decrease" },
      { key: "B", text: "Lift must increase" },
      { key: "C", text: "Lift remains constant" },
    ],
    correct: "B",
  },
  {
    id: "RPA0011",
    aok: "Aircraft Systems",
    text: "What is the primary function of the aircraft's electrical system?",
    choices: [
      { key: "A", text: "To provide ignition power to the engines" },
      { key: "B", text: "To power all essential instruments and avionics" },
      { key: "C", text: "To start the engine and power essential equipment" },
    ],
    correct: "C",
  },
  {
    id: "RPA0012",
    aok: "Aircraft Systems",
    text: "If the alternator fails, how long can an aircraft with typical battery capacity continue operating essential equipment?",
    choices: [
      { key: "A", text: "30 minutes to 2 hours depending on load" },
      { key: "B", text: "Indefinitely at reduced power" },
      { key: "C", text: "Only until the next airport" },
    ],
    correct: "A",
  },
  {
    id: "RPA0013",
    aok: "Flight Instruments",
    text: "What does the vertical speed indicator show?",
    choices: [
      { key: "A", text: "Rate of change of altitude in feet per minute" },
      { key: "B", text: "Current altitude in thousands of feet" },
      { key: "C", text: "Rate of descent only, not climb" },
    ],
    correct: "A",
  },
  {
    id: "RPA0014",
    aok: "Flight Instruments",
    text: "When an aircraft climbs, which way does the needle on an altimeter move?",
    choices: [
      { key: "A", text: "Downward" },
      { key: "B", text: "Upward" },
      { key: "C", text: "It depends on the direction of flight" },
    ],
    correct: "B",
  },
  {
    id: "RPA0015",
    aok: "Aeromedical Factors",
    text: "What is the most reliable prevention for spatial disorientation in flight?",
    choices: [
      { key: "A", text: "Relying on inner ear sensations" },
      { key: "B", text: "Trusting your seat-of-the-pants feeling" },
      { key: "C", text: "Maintaining positive control and frequent reference to instruments" },
    ],
    correct: "C",
  },
  {
    id: "RPA0016",
    aok: "Aeromedical Factors",
    text: "Hypoxia begins to affect judgment and motor control at what altitude for an unacclimatized pilot?",
    choices: [
      { key: "A", text: "5,000 feet MSL" },
      { key: "B", text: "8,000 feet MSL" },
      { key: "C", text: "12,000 feet MSL" },
    ],
    correct: "B",
  },
];
