// AUTO-GENERATED by scripts/download-test-bank.mjs
// Last updated: 2026-03-05T00:00:00.000Z
// Do not edit manually — run the script to regenerate.

import type { TestBankQuestion } from "./test-bank-types";

export const SPG_DATA_UPDATED = "2026-03-05T00:00:00.000Z";

export const SPG_AREAS_OF_KNOWLEDGE = [
  "Regulations",
  "National Airspace System",
  "Weather",
  "Performance and Limitations",
  "Principles of Flight",
  "Flight Instruments",
  "Aeromedical Factors",
] as const;

export const SPG_QUESTIONS: TestBankQuestion[] = [
  {
    id: "SPG0001",
    aok: "Regulations",
    text: "What is the maximum indicated airspeed at which a sport pilot may operate a glider in Class B airspace?",
    choices: [
      { key: "A", text: "200 knots IAS" },
      { key: "B", text: "250 knots IAS" },
      { key: "C", text: "Cannot operate in Class B without specific authorization" },
    ],
    correct: "C",
  },
  {
    id: "SPG0002",
    aok: "Regulations",
    text: "A sport pilot holding a glider rating may tow another glider only if",
    choices: [
      { key: "A", text: "The glider being towed is equipped with dive brakes" },
      { key: "B", text: "A safety pilot occupies the front seat of the towing glider" },
      { key: "C", text: "Both gliders are equipped with military-style oxygen systems" },
    ],
    correct: "B",
  },
  {
    id: "SPG0003",
    aok: "National Airspace System",
    text: "When operating a glider near a Class D airport, what should a pilot do before entering the airspace?",
    choices: [
      { key: "A", text: "Contact approach control on the assigned frequency" },
      { key: "B", text: "Establish two-way radio communication with the tower and receive permission to enter" },
      { key: "C", text: "Simply monitor the tower frequency without transmitting" },
    ],
    correct: "B",
  },
  {
    id: "SPG0004",
    aok: "National Airspace System",
    text: "A glider pilot may descend through a cloud layer in Class E airspace provided",
    choices: [
      { key: "A", text: "Visibility is at least 5 miles and a transponder is installed" },
      { key: "B", text: "IFR clearance is obtained and appropriate instruments are installed" },
      { key: "C", text: "The glider is equipped with a GPS and autopilot" },
    ],
    correct: "B",
  },
  {
    id: "SPG0005",
    aok: "Weather",
    text: "Which atmospheric condition is most favorable for ridge lift in mountainous terrain?",
    choices: [
      { key: "A", text: "Wind flowing perpendicular to ridge with velocity of 8-15 knots" },
      { key: "B", text: "Calm winds with strong thermal activity" },
      { key: "C", text: "Horizontal wind shear with temperature inversion" },
    ],
    correct: "A",
  },
  {
    id: "SPG0006",
    aok: "Weather",
    text: "What is the primary cause of thermals in soaring flight?",
    choices: [
      { key: "A", text: "Horizontal wind shear at altitude" },
      { key: "B", text: "Uneven heating of the Earth's surface creating columns of rising air" },
      { key: "C", text: "Jet stream momentum at high altitude" },
    ],
    correct: "B",
  },
  {
    id: "SPG0007",
    aok: "Performance and Limitations",
    text: "A sport pilot glider has a best glide ratio of 25:1. If the glider is at 4,000 feet AGL, approximately how far can it glide in still air?",
    choices: [
      { key: "A", text: "160 nautical miles" },
      { key: "B", text: "25 nautical miles" },
      { key: "C", text: "100 feet per second" },
    ],
    correct: "A",
  },
  {
    id: "SPG0008",
    aok: "Performance and Limitations",
    text: "What factor has the greatest effect on a glider's stall speed?",
    choices: [
      { key: "A", text: "Bank angle and wing loading" },
      { key: "B", text: "Outside air temperature only" },
      { key: "C", text: "Altitude and barometric pressure" },
    ],
    correct: "A",
  },
  {
    id: "SPG0009",
    aok: "Principles of Flight",
    text: "When thermalling in a glider, a pilot should enter the thermal and establish a turn in the direction",
    choices: [
      { key: "A", text: "Opposite to the wind direction" },
      { key: "B", text: "Into the wind to maximize climb rate" },
      { key: "C", text: "In the direction of the strongest updraft as indicated by sink rate and variometer" },
    ],
    correct: "C",
  },
  {
    id: "SPG0010",
    aok: "Principles of Flight",
    text: "Which control input will induce a spiral dive in a glider if applied too aggressively?",
    choices: [
      { key: "A", text: "Forward pressure on the stick while increasing bank angle" },
      { key: "B", text: "Releasing back pressure while maintaining a turn" },
      { key: "C", text: "Adjusting pitch attitude without coordinated rudder input" },
    ],
    correct: "A",
  },
  {
    id: "SPG0011",
    aok: "Flight Instruments",
    text: "What does a variometer indicate to a glider pilot?",
    choices: [
      { key: "A", text: "The rate of altitude change in feet per minute" },
      { key: "B", text: "The exact altitude above ground level" },
      { key: "C", text: "The glider's airspeed relative to the airmass" },
    ],
    correct: "A",
  },
  {
    id: "SPG0012",
    aok: "Flight Instruments",
    text: "A glider equipped with an electrical variometer loses power during flight. What is the pilot's most appropriate action?",
    choices: [
      { key: "A", text: "Immediately declare an emergency and land" },
      { key: "B", text: "Use the airspeed indicator and altimeter to monitor performance and locate lift" },
      { key: "C", text: "Attempt to restart the variometer by adjusting the circuit breaker" },
    ],
    correct: "B",
  },
  {
    id: "SPG0013",
    aok: "Aeromedical Factors",
    text: "A sport pilot experiences spatial disorientation during a turn in instrument meteorological conditions. The pilot should",
    choices: [
      { key: "A", text: "Trust his inner ear and make small control inputs to recover" },
      { key: "B", text: "Immediately reference the flight instruments and establish straight and level flight" },
      { key: "C", text: "Look outside to regain visual reference with the horizon" },
    ],
    correct: "B",
  },
  {
    id: "SPG0014",
    aok: "Aeromedical Factors",
    text: "At what altitude do most pilots begin to experience the effects of hypoxia during sustained flight?",
    choices: [
      { key: "A", text: "Above 8,000 feet MSL" },
      { key: "B", text: "Above 25,000 feet MSL" },
      { key: "C", text: "Effects begin immediately above ground level" },
    ],
    correct: "A",
  },
];
